// 隔离宿主 + 可控模型；仅使用此脚本生成的合成截图，不代表真实模型识图验证。
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.SNOW_PLAYWRIGHT||'playwright');
const {startMockLlmServer}=await import(process.env.SNOW_MOCK_SERVER);
const server=await startMockLlmServer({port:4342,sequence:['success','success','tool_call_success','success'],repeatLast:true,successText:'截图报价1299元，晚数模糊，请补充购买状态和晚数。',toolName:'snow_save_packages',toolArguments:JSON.stringify({package:{name:'合成雪季套餐',quote:129900,nights:3,purchaseStatus:'unpurchased',pendingQuestions:['有效期未提供']}})});
const url=(await readFile(process.env.SNOW_HOST_LOG,'utf8')).match(/http:\/\/127\.0\.0\.1:\d+[^\s\x1b]*/)?.[0];
const browser=await chromium.launch({headless:true,executablePath:process.env.SNOW_CHROME});
const page=await browser.newPage({viewport:{width:1280,height:960}});page.setDefaultTimeout(20000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
  await mkdir('.local',{recursive:true});
  await page.setContent('<main style="font:32px sans-serif;padding:36px">合成雪季套餐<br>报价：1299 元<br>晚数：<span style="filter:blur(10px)">3</span><br>仅供图片导入测试</main>');
  const png=await page.screenshot({path:'.local/合成套餐.png'});
  await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.snowSessionCheck);
  await page.getByRole('button',{name:'打开雪季出行工作台',exact:true}).click();
  const panel=page.getByRole('dialog',{name:'雪季出行工作台',exact:true});
  await panel.getByRole('button',{name:'出发去山野',exact:true}).click();
  const setupEditor=panel.locator('[contenteditable=true]');await setupEditor.fill('/model');await setupEditor.press('Enter');
  await panel.getByRole('option',{name:/雪季确定性集成检查/}).click();
  await page.waitForFunction(()=>document.querySelector('.snow-conversation [contenteditable=true]')?.textContent==='');
  await panel.getByRole('button',{name:'找出行方案',exact:true}).click();
  assert.equal(await panel.getByRole('button',{name:'套餐与来源',exact:true}).count(),0);
  assert.equal(await panel.getByRole('button',{name:'导入截图',exact:true}).count(),0);
  const before=(await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length;
  await panel.getByRole('button',{name:'出发去山野',exact:true}).click();
  await panel.locator('input[type=file]').setInputFiles({name:'合成套餐.png',mimeType:'image/png',buffer:png});
  const editor=panel.locator('[contenteditable=true]');await editor.waitFor();
  assert.equal(await editor.innerText(),'');
  await panel.locator('img').first().waitFor();
  await page.waitForFunction(()=>[...document.querySelectorAll('.snow-conversation img')].some(img=>img.complete&&img.naturalWidth>0));
  assert.equal(server.requests.length,0);
  assert.equal((await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length,before);
  assert.equal(await page.evaluate(()=>{const s=window.snowSessionCheck.state();return s.byId[s.current].blank;}),true);
  await panel.locator('img').first().click();
  await page.getByRole('dialog',{name:'截图预览',exact:true}).waitFor();
  await page.getByRole('dialog',{name:'截图预览',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();
  await page.screenshot({path:'.local/image-draft.png'});
  await editor.fill('请读取截图，晚数不清楚的先问我。');await editor.press('Enter');
  await panel.locator('[data-chat-flow-kind="assistant-step"]').getByText('截图报价1299元，晚数模糊，请补充购买状态和晚数。',{exact:true}).waitFor();
  const wire=JSON.stringify(server.requests.map(r=>r.body));assert.match(wire,/image_url/);assert.ok(wire.includes('data:image/png;base64,'));
  assert.equal((await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length,before);
  await editor.fill('未购买，3晚。请保存。');await editor.press('Enter');
  await panel.getByText('确认新增套餐',{exact:true}).waitFor();
  const content=await panel.innerText();assert.match(content,/总间夜：3/);
  assert.equal((await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length,before);
  await page.screenshot({path:'.local/image-confirm.png'});
  await panel.getByText('确认保存',{exact:true}).click();await panel.getByRole('button',{name:/提交|发送/}).last().click();
  await page.waitForFunction(()=>{const s=window.snowSessionCheck.state();return !s.byId[s.current]?.running;});
  const process=panel.getByRole('button',{name:'1 次工具调用',exact:true});if(await process.getAttribute('aria-expanded')==='false')await process.click();
  const card=panel.locator('.snow-conversation .snow-package-card');await card.waitFor();
  const id=await card.getAttribute('data-package-id');assert.equal(await card.getByText('资料来源',{exact:true}).count(),0);
  await panel.getByRole('button',{name:'找出行方案',exact:true}).click();await panel.locator(`.snow-content [data-package-id="${id}"]`).waitFor();
  // 独立文字模型拒绝图片；宿主 /model 提供恢复入口，错误不新增记录。
  await panel.getByRole('button',{name:'出发去山野',exact:true}).click();
  await panel.locator('input[type=file]').setInputFiles({name:'合成套餐.png',mimeType:'image/png',buffer:png});
  await editor.fill('/model');await editor.press('Enter');
  await panel.getByRole('option',{name:/仅文字测试模型/}).click();
  await page.waitForFunction(()=>document.querySelector('.snow-conversation [contenteditable=true]')?.textContent==='');
  const count=(await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length;
  await editor.fill('请读取这张截图');await editor.press('Enter');
  await panel.getByRole('alert').filter({hasText:'当前模型不支持图片'}).waitFor();
  assert.match(await panel.innerText(),/does not support image input|不支持.*图片/);
  assert.match(await panel.innerText(),/切换宿主已有兼容模型/);
  assert.equal((await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length,count);
  await page.screenshot({path:'.local/image-unsupported.png'});
  await editor.fill('/model');await editor.press('Enter');
  await panel.getByRole('option',{name:/雪季确定性集成检查/}).click();
  assert.deepEqual(errors,[]);
  console.log('通过：预览草稿不发送，宿主传入图片，多轮补充、确认摘要、卡片不显示来源折叠区且与概览同 ID、仅文字模型拒绝图片且可切换模型。');
  assert.deepEqual(errors,[]);
}catch(error){await page.screenshot({path:'.local/image-failure.png'});console.log((await page.locator('body').innerText()).slice(-3000));throw error;}finally{await browser.close();await server.close();}
