import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import * as React from 'react';
import * as jsx from 'react/jsx-runtime';
import {date,detect,evaluate,money,normalize,readWorkbook} from '../src/ledger.js';
const sheet={name:'台账',rows:[{number:4,cells:['编号','套餐名称','酒店','住宿晚数','订单金额（元）','状态','已购房型','有效期','雪场']},{number:5,cells:['001','测试连住','测试酒店',2,200,'待预约','双床','2026-11-01至2027-03-31','测试雪场']}]};
const detail={name:'001加价',rows:[{number:2,cells:['开始日期','结束日期','加价（元／间／晚）']},{number:3,cells:['2026-12-01','2026-12-05',100]},{number:4,cells:['2026-12-06','2026-12-10',200]}]};
test('台账映射、金额与逐晚边界保持来源；未知不变成零',()=>{
  const raw={fileName:'测试.xlsx',sheets:[sheet,detail]};
  const p=normalize(raw,detect(raw.sheets)).packages[0];
  assert.equal(evaluate(p,'2026-12-05').amount,300);
  assert.equal(evaluate(p,'2026-12-05').end,'2026-12-07');
  assert.equal(evaluate(p,'2026-12-10').amount,null);
  assert.equal(evaluate(p,'2026-12-10').known,200);
  assert.equal(evaluate(p,'2026-12-05',3).eligible,false);
  assert.equal(evaluate(p,'2027-03-31').eligible,false);
  assert.equal(evaluate({...p,rules:[...p.rules,p.rules[0]]},'2026-12-01').amount,null);
  assert.equal(evaluate({...p,blocked:[{from:'2026-12-05',to:'2026-12-05',reason:'不可用'}]},'2026-12-05').eligible,false);
  assert.equal(date('2027-02-29'),null);assert.equal(date('2028-02-29'),'2028-02-29');
  assert.equal(money(''),null);assert.equal(money('0'),0);assert.equal(money('-1'),null);
  assert.equal(money('1,000.50'),1000.5);
  const repeated={...sheet,rows:[...sheet.rows,sheet.rows[1]]};
  assert.equal(normalize({...raw,sheets:[repeated]},detect([repeated])).issues.length,1);
});
test('浏览器产物注册正确包名，工厂仅使用宿主 React',async()=>{
  let handoff;
  vm.runInNewContext(await readFile(new URL('../lib/client.js',import.meta.url),'utf8'),{window:{__ModuleLoader__:{load:v=>{handoff=v;}}},console,setTimeout,clearTimeout,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer});
  assert.equal(handoff.id,'dsh-snow-trip');
  const mod=handoff.factory(id=>{if(id==='react')return React;if(id==='react/jsx-runtime')return jsx;throw Error('非预期外部依赖：'+id);});
  assert.deepEqual(Array.from(mod.inject),['slots','modules','sessions','remote']);assert.equal(typeof mod.apply,'function');
});
test('用户当前工作簿回归（通过 SNOW_TEST_WORKBOOK 显式指定）',{skip:!process.env.SNOW_TEST_WORKBOOK},async()=>{
  const bytes=await readFile(process.env.SNOW_TEST_WORKBOOK);
  const raw=await readWorkbook(bytes,'当前台账.xlsx');
  const data=normalize(raw,detect(raw.sheets));
  assert.equal(data.packages.length,9);
  assert.equal(data.packages.reduce((s,p)=>s+p.nights,0),50);
  assert.equal(data.packages.reduce((s,p)=>s+p.paid+p.paidExtra,0),34813);
  const by=id=>data.packages.find(p=>p.id===id);
  assert.equal(by('003').paidExtra,1000);
  assert.equal(by('008').split,true);assert.equal(by('009').split,true);
  assert.equal(evaluate(by('005'),'2026-12-08').amount,3300);
  assert.equal(evaluate(by('004'),'2026-12-04').amount,6900);
  assert.equal(evaluate(by('007'),'2026-12-04').amount,500);
  assert.equal(evaluate(by('008'),'2026-12-31',1).eligible,false);
  assert.equal(evaluate(by('009'),'2026-10-09',1).eligible,false);
  for(const id of ['001','002','003','006','008','009'])assert.equal(evaluate(by(id),'2026-12-04').amount,null);
});
