// 合成宿主记录 + 真实工作台组件；不连接用户宿主或调用模型。
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
const {chromium}=await import(process.env.SNOW_PLAYWRIGHT||'playwright');
assert.ok(process.env.SNOW_REACT_DOM,'请提供 SNOW_REACT_DOM（react-dom/client.js）');
const script=await build({stdin:{contents:`
import React from 'react';
import {createRoot} from 'react-dom/client';
import {App} from './src/workbench.jsx';
import {storage} from './src/storage.js';
const base={sessionId:'fixture-session',updatedAt:'2026-09-25T00:00:00Z',id:'a',name:'合成套餐 A',description:null,hotels:['合成酒店'],resort:null,region:'吉林',nights:3,paid:10000,paidExtra:30000,quote:null,purchaseStatus:'purchased',completeness:'incomplete',usedNights:0,validFrom:'2026-12-01',validTo:'2026-12-31',unavailableDates:[],unknowns:[],revision:1};
const rows=[base,{...base,id:'b',name:'合成套餐 B',nights:5,paid:0,paidExtra:0,purchaseStatus:'unpurchased',completeness:'complete'},{...base,id:'c',name:'合成套餐 C',paid:null,purchaseStatus:'unknown',region:null},{...base,id:'d',name:'合成套餐 D',nights:null,usedNights:null,validFrom:null,paid:20000,paidExtra:0}];
const workspace={archivedSessionIds:[]};
window.planCheck={hold:true,plans:[{id:'plan-a',sessionId:'fixture-session',createdAt:'2026-09-25T00:00:00Z',items:[{packageId:'a',revision:1},{packageId:'b',revision:1}],packages:[]}]};
const actions={selection:{subscribe:()=>()=>{},getSnapshot:()=>null},lastSession:()=>null,listPackages:async()=>rows,listPlans:async()=>{if(window.planCheck.hold)await new Promise(resolve=>{window.planCheck.release=()=>{window.planCheck.hold=false;resolve();};});return window.planCheck.plans;},workspaceList:{subscribe:()=>()=>{},getSnapshot:()=>workspace}};
window.setLegacy=async present=>{await storage('ledger',present?{fileName:'旧台账.xlsx',packages:[{id:'old',name:'旧套餐',hotel:'旧酒店',resort:'旧雪场',region:'旧地区',nights:2,paid:9999,paidExtra:0,blocked:[],rules:[],split:true}]}:null);};
createRoot(document.getElementById('root')).render(<App useSessionStatus={()=>new Map()} useSessions={()=>({ids:[],byId:{}})} actions={actions} renderSlot={()=>null}/>);
`,resolveDir:process.cwd(),loader:'jsx'},bundle:true,write:false,format:'iife',jsx:'automatic',alias:{react:process.cwd()+'/node_modules/react','react-dom/client':process.env.SNOW_REACT_DOM}});
const html='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{margin:0}</style><style>'+await readFile('node_modules/react-day-picker/src/style.css','utf8')+'\n'+await readFile('src/style.css','utf8')+'</style><div id="root"></div><script>'+script.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></html>';
const server=createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.SNOW_CHROME});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.getByRole('button',{name:/^已录套餐/}).click();
 const cards=page.locator('.package-candidates [data-package-id]');
 const ids=()=>cards.evaluateAll(nodes=>nodes.map(n=>n.dataset.packageId));
 await cards.first().waitFor();assert.deepEqual(await ids(),['a','d','b','c']);
 const planTrigger=page.getByRole('button',{name:/^出行方案：/});
 await planTrigger.click();await page.getByRole('radio',{name:'已有方案',exact:true}).click();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();
 await page.getByText('正在读取出行方案…',{exact:true}).waitFor();
 assert.equal(await cards.count(),0);
 await page.evaluate(()=>window.planCheck.release());
 await cards.first().waitFor();assert.deepEqual(await ids(),['a','b']);
 await planTrigger.click();await page.getByRole('radio',{name:'暂无方案',exact:true}).click();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['d','c']);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 assert.match(await planTrigger.innerText(),/全部/);assert.deepEqual(await ids(),['a','d','b','c']);
 assert.equal(await page.getByLabel('房间补款上限（元）',{exact:true}).count(),0);
 assert.equal(await page.getByRole('option',{name:'录入顺序',exact:true}).count(),0);
 const sortTrigger=page.getByRole('button',{name:/^排序：/});
 assert.match(await sortTrigger.innerText(),/累计已支付/);
 // A 本价低于 D，但加上已付补款后累计金额更高；C 金额未知。
 await sortTrigger.click();await page.getByRole('radio',{name:'住宿晚数',exact:true}).click();
 assert.deepEqual(await ids(),['b','a','c','d']);
 const ascending=()=>page.getByRole('button',{name:'当前降序，切换为升序',exact:true});
 const descending=()=>page.getByRole('button',{name:'当前升序，切换为降序',exact:true});
 await ascending().click();assert.deepEqual(await ids(),['a','c','b','d']);
 await sortTrigger.click();
 assert.deepEqual(await page.getByRole('radiogroup',{name:'排序',exact:true}).getByRole('radio').evaluateAll(nodes=>nodes.map(node=>node.parentElement.textContent)),['住宿晚数','累计已支付']);
 await page.getByRole('radio',{name:'累计已支付',exact:true}).click();assert.deepEqual(await ids(),['b','d','a','c']);
 await descending().click();assert.deepEqual(await ids(),['a','d','b','c']);
 await sortTrigger.click();await page.getByRole('radio',{name:'住宿晚数',exact:true}).click();
 assert.deepEqual(await ids(),['b','a','c','d']);
 await sortTrigger.click();await page.getByRole('radio',{name:'累计已支付',exact:true}).click();
 assert.deepEqual(await ids(),['a','d','b','c']);
 await ascending().focus();await page.keyboard.press('Enter');assert.deepEqual(await ids(),['b','d','a','c']);
 await page.locator('.snow-package-sort').screenshot({path:'.local/package-sort-desktop.png'});
 const tags=page.getByRole('button',{name:/^套餐标签：/});
 assert.equal(await page.getByRole('checkbox',{name:'已购买',exact:true}).isVisible(),false);
 await tags.focus();await page.keyboard.press('Enter');
 await page.getByRole('checkbox',{name:'已购买',exact:true}).focus();await page.keyboard.press('Space');
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['d','a']);
 assert.match(await tags.innerText(),/已购买/);
 await tags.click();await page.getByRole('checkbox',{name:'未购买',exact:true}).check();
 await page.getByRole('checkbox',{name:'资料完整',exact:true}).check();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['b']);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();assert.deepEqual(await ids(),['b','d','a','c']);
 const dateTrigger=page.getByRole('button',{name:/^入住日期：/}),calendar=page.getByRole('group',{name:'入住日期选项',exact:true});
 await dateTrigger.click();
 await calendar.getByLabel('选择年份',{exact:true}).selectOption('2026');
 await calendar.getByLabel('选择月份',{exact:true}).selectOption('11');
 await calendar.getByRole('button',{name:'2026-12-29',exact:true}).click();
 assert.match(await dateTrigger.innerText(),/2026-12-29/);
 assert.equal(await dateTrigger.evaluate(node=>node===document.activeElement),true);
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['a','c']);
 await dateTrigger.click();await calendar.getByRole('button',{name:'清空日期'}).click();
 assert.match(await dateTrigger.innerText(),/不限日期/);
 await tags.click();await page.getByRole('checkbox',{name:'待补全',exact:true}).check();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['d','a','c']);
 await page.getByRole('button',{name:/^目的地区域：/}).click();await page.getByRole('radio',{name:'吉林',exact:true}).click();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['d','a']);
 await page.getByLabel('搜索套餐或酒店',{exact:true}).fill('不存在');
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.equal(await cards.count(),0);
 await page.getByRole('button',{name:'重置筛选',exact:true}).first().click();
 for(const present of [true,false]){
   await page.evaluate(present=>window.setLegacy(present),present);await page.reload();await page.getByRole('button',{name:/^已录套餐/}).click();await cards.first().waitFor();
   assert.deepEqual(await ids(),['a','d','b','c']);
   assert.equal(await page.getByRole('radio',{name:'旧地区',exact:true}).count(),0);
 }
 for(const width of [1440,681,390]){
   await page.setViewportSize({width,height:900});
   if(width<=760&&await page.getByRole('button',{name:/筛选出行/}).getAttribute('aria-expanded')==='false')await page.getByRole('button',{name:/筛选出行/}).click();
   const styles=await page.locator('.filter-grid .field>select,.filter-grid .package-tag-trigger').evaluateAll(nodes=>nodes.map(node=>{
     const style=getComputedStyle(node);return ['height','borderRadius','paddingLeft','paddingRight','fontSize','fontWeight','backgroundImage','backgroundPosition'].map(key=>style[key]);
   }));
   const before=await ids(),direction=await ascending().locator('path').getAttribute('d');
   await ascending().click();assert.notEqual(await descending().locator('path').getAttribute('d'),direction);
   await descending().click();assert.deepEqual(await ids(),before);
   if(width===390)await page.locator('.snow-package-sort').screenshot({path:'.local/package-sort-mobile.png'});
   assert.equal(styles.length,5);assert.deepEqual(styles[0],styles[1]);assert.deepEqual(styles[1],styles[2]);
 }
 await page.getByRole('button',{name:/筛选出行/}).click();
 await page.setViewportSize({width:390,height:844});
 const toggle=page.getByRole('button',{name:/筛选出行/});await toggle.click();
 await tags.click();await page.getByRole('checkbox',{name:'待确认',exact:true}).check();
 await page.getByRole('button',{name:'查找套餐',exact:true}).click();assert.deepEqual(await ids(),['c']);
 assert.equal(await toggle.getAttribute('aria-expanded'),'false');
 await toggle.click();await tags.click();await page.getByRole('checkbox',{name:'待确认',exact:true}).focus();await page.keyboard.press('Space');
 assert.equal(await page.getByRole('checkbox',{name:'待确认',exact:true}).isChecked(),false);
 await page.keyboard.press('Escape');
 assert.equal(await tags.evaluate(el=>document.activeElement===el),true);
 assert.equal(await page.getByRole('checkbox',{name:'待确认',exact:true}).isVisible(),false);
 await tags.click();
 const bounds=await page.locator('.package-tag-options:popover-open').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);
 assert.equal(await page.locator('.snow-content').evaluate(el=>el.scrollWidth>el.clientWidth),false);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:/^住宿晚数：/}).click();
 await page.getByRole('radio',{name:'2 晚',exact:true}).click();
 assert.equal(await page.locator('.package-tag-options:popover-open').count(),0);
 assert.match(await page.getByRole('button',{name:/^住宿晚数：/}).innerText(),/2 晚/);
 await page.getByRole('button',{name:/^住宿晚数：/}).click();
 assert.equal(await page.getByRole('radiogroup',{name:'住宿晚数',exact:true}).locator('input:checked').count(),1);
 const optionStyles=await page.locator('.package-tag-options label').evaluateAll(nodes=>nodes.map(n=>{const s=getComputedStyle(n);return [s.minHeight,s.padding,s.fontSize];}));
 assert.ok(optionStyles.every(style=>JSON.stringify(style)===JSON.stringify(optionStyles[0])));
 await mkdir('.local/snow-10',{recursive:true});
 await page.screenshot({path:'.local/snow-10/mobile.png'});
 await dateTrigger.click();
 await calendar.getByLabel('选择年份',{exact:true}).selectOption('2026');
 await calendar.getByLabel('选择月份',{exact:true}).selectOption('11');
 await calendar.getByRole('button',{name:'2026-12-20',exact:true}).focus();
 await page.keyboard.press('ArrowRight');
 await page.screenshot({path:'.local/package-date-single-mobile.png'});
 await page.keyboard.press('Enter');
 assert.match(await dateTrigger.innerText(),/2026-12-21/);
 assert.deepEqual(errors,[]);
 console.log('通过：真实工作台组件筛选、标签组合、排序、重置、旧台账隔离、键盘和 390px 窄屏；未连接真实宿主。');
}finally{try{await browser?.close();}finally{await new Promise(resolve=>server.close(resolve));}}
