// 仅使用合成数据；SNOW_PLAYWRIGHT、SNOW_REACT_DOM 指向已有依赖。
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile,mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.SNOW_PLAYWRIGHT||'playwright');
const script=await build({stdin:{contents:`
import React from 'react';import {createRoot} from ${JSON.stringify(process.env.SNOW_REACT_DOM||'react-dom/client')};
import {App} from './src/workbench.jsx';import {normalizePackage} from './src/packages.ts';import {storage} from './src/storage.js';
const id='11111111-1111-4111-8111-111111111111',createdAt='2026-09-25T00:00:00Z';
const pkg={...normalizePackage({name:'测试套餐'}),id,revision:1,schemaVersion:1,createdAt,updatedAt:createdAt,sessionId:'test'};
const plan={id,schemaVersion:1,createdAt,sessionId:'test',title:'删除验收方案',start:'2027-02-06',nights:7,budget:null,total:10000,paid:null,pending:null,reason:null,allocation:null,estimates:[],items:[{packageId:id,revision:1,nights:7,start:'2027-02-06'}],daily:[{date:'2027-02-06',packageId:id,amount:10000,basis:null}],sharedCosts:[],unknowns:[],packages:[{id,revision:1,snapshot:pkg}]};
window.check={template:plan,plans:[plan],packages:[{...pkg,name:'最新套餐名称',revision:2}],fail:false,calls:0,prompt:null,missing:false,created:0};
const workspace={archivedSessionIds:[]},sessions={byId:{test:{id:'test',title:'关联会话',projectionValues:{agentPreset:'snow-trip'}}},ids:['test']};
const actions={lastSession:()=>null,workspaceList:{subscribe:()=>()=>{},getSnapshot:()=>workspace},listPackages:async()=>window.check.packages,listPlans:async()=>[...window.check.plans],sessionState:()=>null,continueRecord:async(record,prompt)=>{if(window.check.missing)return false;window.check.prompt=prompt;sessions.current=record.sessionId;render();return true;},create:async prompt=>{window.check.created++;window.check.prompt=prompt;},deletePlan:async id=>{window.check.calls++;await new Promise(r=>setTimeout(r,100));if(window.check.fail)throw new Error('模拟写入失败');window.check.plans=window.check.plans.filter(p=>p.id!==id);}};
await storage('plans',[{id:'legacy',title:'不应显示的旧方案'}]);
const root=createRoot(document.getElementById('root'));function render(){root.render(<App useSessions={()=>sessions} renderSlot={()=>null} actions={actions}/>);}render();
`,resolveDir:process.cwd(),loader:'jsx'},bundle:true,write:false,format:'esm',alias:{react:process.cwd()+'/node_modules/react'},jsx:'automatic'});
const browser=await chromium.launch({headless:true,executablePath:process.env.SNOW_CHROME});
try{
 const page=await browser.newPage({viewport:{width:1061,height:863}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(5000);
 await page.route('http://snow.test/',route=>route.fulfill({body:'<meta charset="utf-8"><div id="root"></div>',contentType:'text/html'}));
 await page.goto('http://snow.test/');await page.addStyleTag({content:await readFile('src/style.css','utf8')});await page.addScriptTag({type:'module',content:script.outputFiles[0].text});
 await page.getByRole('button',{name:'查看套餐详情：最新套餐名称',exact:true}).click();
 const explorePanel=page.getByRole('complementary',{name:'关联详情'});
 await explorePanel.getByRole('heading',{name:'套餐详情',exact:true}).waitFor();
 assert.equal(await page.locator('.package-more').count(),0);
 assert.equal(await page.locator('.package-candidates .package-trip-notes').count(),0);
 await explorePanel.getByRole('complementary',{name:'本次出行核对提示'}).waitFor();
 assert.equal(await explorePanel.locator('.snow-detail-section').first().getAttribute('open'),'');
 await explorePanel.getByRole('button',{name:'收起套餐详情',exact:true}).click();
 await page.getByRole('button',{name:'删除套餐',exact:true}).waitFor();
 await page.getByRole('button',{name:'删除套餐',exact:true}).click();
 const packageDialog=page.getByRole('dialog',{name:'删除套餐',exact:true});
 await packageDialog.getByText('删除验收方案',{exact:false}).waitFor();
 assert.match(await packageDialog.innerText(),/1 份方案.*一并永久删除/s);
 await packageDialog.getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:/^已存方案/}).click();
 const card=page.locator('.snow-saved-card'),dialog=page.getByRole('dialog',{name:'删除方案',exact:true});await card.waitFor();
 assert.match(await page.locator('h1').innerText(),/1 份/);assert.equal(await page.getByText('不应显示的旧方案').count(),0);
 await page.getByRole('region',{name:'出行方案',exact:true}).getByText('已存 1 份',{exact:true}).waitFor();
 assert.equal(await card.locator('.snow-plan-packages').count(),0);
 let panel;
 await card.getByRole('button',{name:'继续规划'}).click();
 await page.locator('.snow-session-main').waitFor();assert.match(await page.evaluate(()=>window.check.prompt),/"type":"plan".*11111111/s);
 panel=page.getByRole('complementary',{name:'关联详情'});await panel.getByRole('button',{name:'套餐 1',exact:true}).click();await panel.getByText('最新套餐名称',{exact:true}).waitFor();
 await panel.getByRole('button',{name:'方案 1',exact:true}).click();await panel.getByRole('button',{name:/测试套餐 · 第 1 版/}).click();
 await panel.getByRole('button',{name:'查看最新资料',exact:true}).click();assert.equal(await page.locator('.snow-session-open[aria-current="page"]').getAttribute('title'),'关联会话');
 await page.getByRole('button',{name:/^已存方案/}).click();
 await page.getByRole('button',{name:/^已录套餐/}).click();
 await page.locator('.snow-package-card').getByRole('button',{name:/继续补全|补充信息/}).click();await page.locator('.snow-session-main').waitFor();assert.match(await page.evaluate(()=>window.check.prompt),/"type":"package".*11111111/s);
 await page.evaluate(()=>{window.check.keptPackages=window.check.packages;window.check.packages=[];});
 await page.getByRole('button',{name:/^已存方案/}).click();await card.getByRole('button',{name:'继续规划'}).click();await page.getByRole('complementary',{name:'关联详情'}).getByRole('button',{name:/测试套餐 · 第 1 版/}).click();
 await page.getByRole('complementary',{name:'关联详情'}).getByText('原套餐已删除，仍可查看保存时快照。',{exact:true}).waitFor();
 await page.getByRole('complementary',{name:'关联详情'}).getByRole('button',{name:'收起套餐详情',exact:true}).click();
 await page.evaluate(()=>window.check.packages=window.check.keptPackages);
 await page.evaluate(()=>window.check.packages=[window.check.plans[0].packages[0].snapshot]);
 await page.getByRole('button',{name:/^已录套餐/}).click();await page.getByRole('button',{name:/^已存方案/}).click();
 await card.getByRole('button',{name:'继续规划'}).click();await page.getByRole('complementary',{name:'关联详情'}).getByRole('button',{name:/测试套餐 · 第 1 版/}).click();
 panel=page.getByRole('complementary',{name:'关联详情'});await panel.getByText('已是最新资料',{exact:true}).waitFor();
 assert.equal(await panel.getByRole('button',{name:'查看最新资料',exact:true}).count(),0);
 assert.equal(await panel.getByRole('button',{name:'查看保存时快照',exact:true}).count(),0);
 await panel.getByRole('button',{name:'收起套餐详情',exact:true}).click();
 await page.getByRole('button',{name:/^已存方案/}).click();
 await page.evaluate(()=>window.check.missing=true);await card.getByRole('button',{name:'继续规划'}).click();
 const unavailable=page.getByRole('dialog',{name:'原会话不可用'});await unavailable.waitFor();assert.equal(await page.evaluate(()=>window.check.created),0);
 await unavailable.getByRole('button',{name:'取消',exact:true}).click();
 await card.getByRole('button',{name:'继续规划'}).click();await unavailable.getByRole('button',{name:'新建会话继续'}).click();await unavailable.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>window.check.created),1);
 await page.getByRole('button',{name:/^已存方案/}).click();
 const buttons=card.locator('.package-actions');assert.equal(await buttons.getByRole('button').count(),2);
 const left=await buttons.getByRole('button',{name:'继续规划'}).boundingBox(),right=await buttons.getByRole('button',{name:'删除方案'}).boundingBox();assert.ok(left.x<right.x);assert.equal(left.y,right.y);
 await card.getByRole('button',{name:'删除方案'}).click();assert.match(await dialog.innerText(),/删除验收方案.*无法恢复/s);
 await dialog.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await page.evaluate(()=>window.check.calls),0);
 await page.evaluate(()=>window.check.fail=true);await card.getByRole('button',{name:'删除方案'}).click();await dialog.getByRole('button',{name:'确认删除'}).click();
 await dialog.getByRole('button',{name:'正在删除…'}).waitFor();assert.equal(await dialog.getByRole('button',{name:'取消',exact:true}).isDisabled(),true);
 await dialog.getByRole('alert').waitFor();assert.match(await dialog.innerText(),/模拟写入失败/);assert.equal(await card.count(),1);
 await dialog.getByRole('button',{name:'取消',exact:true}).click();await page.setViewportSize({width:390,height:844});
 await mkdir('.local',{recursive:true});await buttons.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/plan-delete-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>window.check.fail=false);await card.getByRole('button',{name:'删除方案'}).click();await dialog.getByRole('button',{name:'确认删除'}).click();await dialog.waitFor({state:'detached'});await card.waitFor({state:'detached'});
 assert.match(await page.locator('h1').innerText(),/0 份/);await page.getByText('还没有保存的方案',{exact:true}).waitFor();
 await page.getByRole('button',{name:/^已录套餐/}).click();await page.locator('.snow-package-card').waitFor();assert.deepEqual(errors,[]);
 await page.evaluate(()=>{window.check.missing=false;window.check.packages=[];window.check.plans=[window.check.template,{...window.check.template,id:'22222222-2222-4222-8222-222222222222',title:'另一份出行方案'}];});
 await page.getByRole('button',{name:/^已存方案/}).click();await page.locator('.snow-saved-entry').first().getByRole('button',{name:'继续规划'}).click();
 panel=page.getByRole('complementary',{name:'关联详情'});
 const plans=panel.locator('.snow-detail-plan');await plans.nth(1).waitFor();
 assert.equal(await plans.nth(0).evaluate(e=>e.open),true);assert.equal(await plans.nth(1).evaluate(e=>e.open),false);
 assert.equal(await panel.locator('.snow-detail-tabs').getByText('套餐',{exact:true}).count(),0);
 await plans.nth(0).locator('summary').click();await plans.nth(1).locator('summary').click();
 assert.equal(await plans.nth(0).evaluate(e=>e.open),false);assert.equal(await plans.nth(1).evaluate(e=>e.open),true);
 assert.equal(await plans.nth(1).locator('h3').count(),0);
 await page.setViewportSize({width:1512,height:863});await panel.screenshot({path:'.local/multiple-plans-taste.png'});
 assert.deepEqual(errors,[]);
 console.log('通过：会话分组、原会话预填、缺失会话手动新建、方案引用快照与最新资料切换、底部按钮布局、旧方案不展示、取消、失败保留、提交禁用、删除后计数与空态、套餐保留、窄屏布局。');
}finally{await browser.close();}
