import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,rename,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Context} from '@deepseek-ai/cordis';
import {createScope,bindScopeParent} from '@deepseek-ai/dsh-scope';
import * as SnowTools from 'dsh-snow-trip/tools';
import {TYPERT} from '../lib/typert.host.js';
import Tools from '@deepseek-ai/dsh-tools';
import SystemPrompt from '@deepseek-ai/dsh-system-prompt';
import Storage from '@deepseek-ai/dsh-storage';
import * as StorageJson from '@deepseek-ai/dsh-storage-json';
import * as StorageDomain from '@deepseek-ai/dsh-storage-domain';
import {SnowTrip} from '../lib/service.js';
import {packageMetadata} from '../src/packages.ts';

test('公开工具：卡片确认→保存→重开→查询；变更、取消和写盘失败无成功 metadata',async()=>{
  const root=await mkdtemp(join(tmpdir(),'snow-import-'));
  let ctx,owner,presetScope,secondAgent,calls=0;
  const archived=[];
  let onArchive=async()=>{};
  let onQuestion=async request=>({answers:[{id:request.questions[0].id,selected:['确认保存']}]});
  async function boot(){
    const rootContext=new Context();
    owner=rootContext.plugin({async apply(scope){ctx=scope;
    await ctx.plugin(SystemPrompt);await ctx.plugin(Tools);
    await ctx.plugin(Storage);await ctx.plugin(StorageJson,{root});await ctx.plugin(StorageDomain,{backend:'json'});
    ctx.provide('userQuestions',{ask:async request=>{calls++;return onQuestion(request);}});
    ctx.provide('workspaceRegistry',{archiveSession:async id=>{await onArchive();archived.push(id);}});
    await ctx.plugin(SnowTrip);
    }});await owner;ctx=rootContext;
    assert.equal(ctx.tools.schemas().some(tool=>tool.name.startsWith('snow_')),false,'宿主层不应注册雪季工具');
    agent={...agent};secondAgent={...agent,id:'second-session'};
    await ctx.snowTrip.listPackages();
    const presetKey={};
    await ctx.plugin({inject:['snowTrip','tools','userQuestions'],async apply(inner){
      presetScope=createScope(inner,presetKey);
      await presetScope.ctx.plugin(SnowTools);
    }});
    bindScopeParent(agent,presetKey);bindScopeParent(secondAgent,presetKey);
    assert.deepEqual(ctx.tools.schemas(agent).map(t=>t.name).sort(),['snow_extra_payment','snow_query','snow_query_plan','snow_list_plans','snow_rename_plan','snow_update_plan','snow_update_plan_tracking','snow_draft','snow_draft_get','snow_draft_discard','snow_set_basic','snow_set_benefits','snow_set_purchase','snow_set_usage','snow_hotel','snow_surcharge','snow_unavailable_date','snow_other_benefit','snow_pending_question','snow_clear_field','snow_commit','snow_evaluate','snow_save_plan','snow_plan_stage','snow_prepare_plan','snow_plan_results'].sort());
    assert.deepEqual(ctx.tools.schemas(secondAgent).map(t=>t.name).sort(),['snow_extra_payment','snow_query','snow_query_plan','snow_list_plans','snow_rename_plan','snow_update_plan','snow_update_plan_tracking','snow_draft','snow_draft_get','snow_draft_discard','snow_set_basic','snow_set_benefits','snow_set_purchase','snow_set_usage','snow_hotel','snow_surcharge','snow_unavailable_date','snow_other_benefit','snow_pending_question','snow_clear_field','snow_commit','snow_evaluate','snow_save_plan','snow_plan_stage','snow_prepare_plan','snow_plan_results'].sort());
    assert.deepEqual(ctx.tools.schemas({id:'ordinary-session'}),[]);
    assert.deepEqual(ctx.tools.schemas(),[]);
    const denied=await ctx.tools.execute({name:'snow_query',arguments:{},agent:{id:'ordinary-session'},signal:new AbortController().signal,callId:'denied'});
    assert.equal(denied.isError,true);
    return ctx.snowTrip.listPackages();
  }
  let agent={id:'test-session'};
  const execute=(name,args,signal=new AbortController().signal)=>ctx.tools.execute({name,arguments:args,agent,signal,callId:`call-${Math.random()}`});
  const ok=async(name,args)=>{const r=await execute(name,args);assert.equal(r.isError,false,JSON.stringify(r));return r;};
  try{
    assert.deepEqual(await boot(),[]);
    assert.ok(!ctx.tools.schemas(agent).some(t=>t.name==='snow_save_packages'));
    const {draftId}= (await ok('snow_draft',{})).value;
    assert.equal((await ok('snow_draft',{})).value.draftId,draftId,'重试创建不丢失草稿');
    let payment=(await ok('snow_extra_payment',{draftId,action:'upsert',purpose:'周末补款',scope:'date',date:'2027-02-04',rooms:1,paid:200,total:400,settled:false,basis:'用户确认本晚已付200元，尚需200元'})).value;
    const paymentId=payment.package.extraPayments[0].id;
    assert.equal(payment.package.extraPayments[0].paid,200);
    assert.equal((await execute('snow_extra_payment',{draftId,action:'upsert',id:paymentId,date:'2027-02-06'})).isError,true);
    payment=(await ok('snow_extra_payment',{draftId,action:'upsert',id:paymentId,date:'2027-02-06',transferConfirmed:true})).value;
    assert.equal(payment.package.extraPayments[0].date,'2027-02-06');
    assert.equal((await execute('snow_extra_payment',{draftId,action:'upsert',paid:-1})).isError,true);
    await ok('snow_extra_payment',{draftId,action:'none'});
    await ok('snow_set_basic',{draftId,description:'长白山住宿'});
    await ok('snow_set_purchase',{draftId,quote:1299.50,purchaseStatus:'unpurchased'});
    await ok('snow_set_usage',{draftId,nights:3});
    await ok('snow_set_benefits',{draftId,skiIncluded:true,skiTickets:2,skiBasis:'night',breakfastIncluded:true,breakfastPeople:2,breakfastBasis:'day',spaIncluded:false,splitAllowed:true});
    await ok('snow_set_basic',{draftId,splitRule:'每次至少住2晚'});
    await ok('snow_hotel',{draftId,action:'add',value:'长白山酒店'});
    await ok('snow_hotel',{draftId,action:'add',value:'长白山酒店'});
    await ok('snow_unavailable_date',{draftId,action:'none'});
    await ok('snow_other_benefit',{draftId,action:'add',value:'晚餐券2张，入住期间使用'});
    const draft=(await ok('snow_draft_get',{draftId})).value;
    assert.deepEqual(draft.package.hotels,['长白山酒店']);assert.equal(draft.package.quote,1299.5);
    for(const [name,args] of [
      ['snow_set_usage',{draftId,nights:'3'}],['snow_set_purchase',{draftId,quote:1.005}],
      ['snow_hotel',{draftId,action:'add',value:[['酒店']]}],['snow_set_basic',{draftId,source:'test'}],
      ['snow_unavailable_date',{draftId,action:'add',value:'2026-02-30'}],
      ['snow_hotel',{draftId,action:'remove',value:'不存在'}],
    ]){const r=await execute(name,args);assert.equal(r.isError,true,JSON.stringify(r));assert.equal(r.meta,undefined);}
    const errorText=r=>r.content.filter(c=>c.type==='text').map(c=>c.text).join('\n');
    assert.match(errorText(await execute('snow_set_purchase',{draftId,paid:1.005})),/paid.*1.005/);
    assert.match(errorText(await execute('snow_set_usage',{draftId,nights:'3'})),/nights.*integer.*3/);
    assert.match(errorText(await execute('snow_unavailable_date',{draftId,action:'add',value:'bad'})),/2026-12-25/);
    assert.match(errorText(await execute('snow_query',{limit:'20'})),/limit.*integer.*20/);
    assert.deepEqual((await ok('snow_draft_get',{draftId})).value,draft,'失败步骤不改写已有草稿');
    const denied=await ctx.tools.execute({name:'snow_draft_get',arguments:{draftId},agent:secondAgent,signal:new AbortController().signal,callId:'isolation'});
    assert.equal(denied.isError,true);assert.equal(calls,0);assert.deepEqual(await ctx.snowTrip.listPackages(),[]);
    onQuestion=async request=>({answers:[{id:request.questions[0].id,selected:['取消本次操作']}]});
    const cancelled=await ok('snow_commit',{draftId});
    assert.equal(cancelled.concludesTurn,true);assert.equal(cancelled.meta.status,'cancelled');assert.equal(cancelled.meta.record,null);assert.deepEqual(await ctx.snowTrip.listPackages(),[]);
    onQuestion=async request=>({answers:[{id:request.questions[0].id,selected:['继续调整']}]});
    const adjusted=await ok('snow_commit',{draftId});
    assert.equal(adjusted.concludesTurn,true);assert.equal(adjusted.meta.preview.nights,3);assert.deepEqual(adjusted.meta.preview.otherBenefits,['晚餐券2张，入住期间使用']);assert.equal(adjusted.value.status,'adjusting');assert.equal(packageMetadata(adjusted.meta),null);
    assert.deepEqual(await ctx.snowTrip.listPackages(),[]);
    onQuestion=async request=>{const preview=JSON.parse(request.questions[0].detail);assert.equal(preview.preview.quote,129950);return {answers:[{id:request.questions[0].id,selected:['确认保存']}]};};
    calls=0;
    const success=await ok('snow_commit',{draftId}),record=packageMetadata(success.meta);
    onQuestion=async request=>({answers:[{id:request.questions[0].id,selected:['确认保存']}]});
    const modelSaved=JSON.parse(success.content.find(c=>c.type==='text').text);
    assert.equal(modelSaved.quote,1299.5);assert.equal(modelSaved.amountUnit,'元');
    const savedDraft=(await ok('snow_draft_get',{draftId})).value;assert.equal(savedDraft.id,record.id);assert.equal(savedDraft.expectedRevision,1);
    assert.equal(record.skiTickets,2);assert.equal(record.skiBasis,'night');assert.equal(record.breakfastPeople,2);assert.equal(record.spaIncluded,false);assert.equal(record.splitAllowed,true);
    assert.ok(record);assert.equal(record.quote,129950);assert.equal(record.nights,3);assert.equal(record.paid,null);
    assert.equal(calls,1,'写入前必须确认');assert.equal('sources' in record,false);
    assert.equal((await ok('snow_commit',{draftId})).value.id,record.id);
    assert.equal((await ctx.snowTrip.listPackages()).length,1,'提交重试不重复新增');
    assert.equal((await execute('snow_set_basic',{draftId,name:'不可修改'})).isError,true);
    const query=await ok('snow_query',{});assert.equal(query.value.packages[0].quote,1299.5);assert.equal(query.value.amountUnit,'元');
    await owner.dispose();await boot();assert.deepEqual(await ctx.snowTrip.getPackage(record.id),record);
    const update=(await ok('snow_draft',{id:record.id,expectedRevision:1})).value.draftId;
    await ok('snow_set_purchase',{draftId:update,purchasePlatform:'微信小程序 xxx'});
    await ok('snow_unavailable_date',{draftId:update,action:'add',value:'2026-12-25'});
    await ok('snow_pending_question',{draftId:update,action:'add',value:'房型待确认'});
    await ok('snow_pending_question',{draftId:update,action:'remove',value:'房型待确认'});
    await ok('snow_clear_field',{draftId:update,field:'description'});
    // 写入期间拒绝编辑和再次提交，保证保存快照不变。
    let release,started;const gate=new Promise(resolve=>{started=resolve;});
    const save=ctx.snowTrip.savePackage.bind(ctx.snowTrip);
    ctx.snowTrip.savePackage=async(...args)=>{started();await new Promise(resolve=>{release=resolve;});return save(...args);};
    const committing=execute('snow_commit',{draftId:update});await gate;
    assert.equal((await execute('snow_set_usage',{draftId:update,nights:5})).isError,true);
    assert.equal((await execute('snow_commit',{draftId:update})).isError,true);
    release();const updated=await committing;ctx.snowTrip.savePackage=save;assert.equal(updated.isError,false);
    assert.equal(updated.value.revision,2);assert.equal(updated.value.description,null);assert.equal(updated.value.quote,129950);
    assert.deepEqual(updated.value.unavailableDates,['2026-12-25']);
    const stale=(await ok('snow_draft',{id:record.id,expectedRevision:2})).value.draftId;
    onQuestion=async request=>{await ctx.snowTrip.savePackage({...updated.value,revision:3},2);return {answers:[{id:request.questions[0].id,selected:['确认保存']}]};};
    assert.equal((await execute('snow_commit',{draftId:stale})).isError,true,'确认期间版本变化也不能覆盖');
    assert.equal((await ctx.snowTrip.getPackage(record.id)).revision,3);
    onQuestion=async request=>({answers:[{id:request.questions[0].id,selected:['确认保存']}]});
    const before=calls;assert.equal((await execute('snow_commit',{draftId:stale})).isError,true);assert.equal(calls,before);
    await ok('snow_draft_discard',{draftId:stale});
    assert.equal((await execute('snow_draft_get',{draftId:stale})).isError,true);
    const fresh=(await ok('snow_draft',{})).value.draftId;
    await ok('snow_set_basic',{draftId:fresh,name:'第二份套餐'});
    await ok('snow_set_purchase',{draftId:fresh,purchaseStatus:'unpurchased',paid:1});
    assert.equal((await execute('snow_commit',{draftId:fresh})).isError,true,'跨字段冲突在统一提交前拦截');
    await ok('snow_clear_field',{draftId:fresh,field:'paid'});
    const controller=new AbortController();controller.abort();
    assert.equal((await execute('snow_commit',{draftId:fresh},controller.signal)).isError,true);
    await rename(join(root,'snow_trip.json'),join(root,'saved.json'));await mkdir(join(root,'snow_trip.json'));
    const failure=await execute('snow_commit',{draftId:fresh});assert.equal(failure.isError,true);assert.equal(failure.meta,undefined);
    assert.equal((await ctx.snowTrip.listPackages()).length,1);
    await rm(join(root,'snow_trip.json'),{recursive:true});await rename(join(root,'saved.json'),join(root,'snow_trip.json'));
    await ok('snow_commit',{draftId:fresh});
    assert.equal((await ok('snow_query',{limit:1})).value.truncated,true);
    await assert.rejects(ctx.snowTrip.archiveSession(record.sessionId),/有关联套餐/);
    await assert.rejects(ctx.snowTrip.deletePackage(record.id,2,false),/已变更/);
    await assert.rejects(ctx.snowTrip.deletePackage(record.id,3,true),/关联套餐已变更/);
    await ctx.snowTrip.deletePackage(record.id,3,false);
    const remaining=(await ctx.snowTrip.listPackages())[0];
    let finishArchive,archiveStarted;const startedArchive=new Promise(resolve=>{archiveStarted=resolve;});
    onArchive=()=>{archiveStarted();return new Promise(resolve=>{finishArchive=resolve;});};
    const deleting=ctx.snowTrip.deletePackage(remaining.id,remaining.revision,true);await startedArchive;
    const later={...remaining,id:crypto.randomUUID()};const saving=ctx.snowTrip.savePackage(later);
    await new Promise(resolve=>setImmediate(resolve));assert.equal(await ctx.snowTrip.getPackage(later.id),null);
    finishArchive();await deleting;await saving;
    onArchive=async()=>{throw new Error('归档写盘失败');};
    assert.deepEqual(await ctx.snowTrip.deletePackage(later.id,later.revision,true),{sessionId:null,archiveError:'归档写盘失败'});
    onArchive=async()=>{};await ctx.snowTrip.archiveSession(later.sessionId);
    await owner.dispose();await boot();assert.deepEqual(await ctx.snowTrip.listPackages(),[]);
    const extrasDraft=(await ok('snow_draft',{})).value.draftId;
    await ok('snow_set_basic',{draftId:extrasDraft,name:'补款持久化测试'});
    await ok('snow_set_purchase',{draftId:extrasDraft,purchaseStatus:'purchased',paidExtra:400});
    const extra=(await ok('snow_extra_payment',{draftId:extrasDraft,action:'upsert',purpose:'日期加价',scope:'date',date:'2027-02-04',rooms:1,paid:200,total:300,settled:false,basis:'用户确认'})).value;
    assert.equal(extra.package.paidExtra,400,'未归属的余额不能被一条已知明细覆盖');
    const withExtras=(await ok('snow_commit',{draftId:extrasDraft})).value;
    assert.equal(withExtras.completeness,'incomplete');assert.equal(withExtras.extraPayments[0].paid,20000);
    await owner.dispose();await boot();
    const queriedExtras=(await ok('snow_query',{id:withExtras.id})).value.packages[0];
    assert.equal(queriedExtras.extraPayments[0].paid,200);assert.equal(queriedExtras.extraPayments[0].total,300);assert.equal(queriedExtras.paidExtra,400);
    await presetScope.dispose();assert.deepEqual(ctx.tools.schemas(agent),[]);
  }finally{await owner?.dispose();await rm(root,{recursive:true,force:true});}
});
