import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,rename,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Context} from '@deepseek-ai/cordis';
import {createScope,bindScopeParent} from '@deepseek-ai/dsh-scope';
import * as SnowTools from 'dsh-snow-trip/tools';
import {TYPERT} from '../lib/typert.host.js';
import Tools from '@deepseek-ai/dsh-tools';
import SystemPrompt from '@deepseek-ai/dsh-system-prompt';
import Storage from '@deepseek-ai/dsh-storage';
import * as StorageJson from '@deepseek-ai/dsh-storage-json';
import * as StorageDomain from '@deepseek-ai/dsh-storage-domain';
import {SnowTrip} from '../lib/service.js';
import {packageMetadata} from '../src/packages.ts';

test('公开工具：确认→写入→重开→查询；拒绝、伪造、变更、取消和写盘失败无成功 metadata',async()=>{
  const root=await mkdtemp(join(tmpdir(),'snow-import-'));
  let ctx,owner,presetScope,secondAgent,calls=0,respond=()=>({answers:[{id:'save-package',selected:['确认保存']}]});
  let question;
  const archived=[];
  let onArchive=async()=>{};
  async function boot(){
    const rootContext=new Context();
    owner=rootContext.plugin({async apply(scope){ctx=scope;
    await ctx.plugin(SystemPrompt);await ctx.plugin(Tools);
    await ctx.plugin(Storage);await ctx.plugin(StorageJson,{root});await ctx.plugin(StorageDomain,{backend:'json'});
    ctx.provide('userQuestions',{ask:async request=>{calls++;question=request.questions[0].detail;return respond();}});
    ctx.provide('workspaceRegistry',{archiveSession:async id=>{await onArchive();archived.push(id);}});
    await ctx.plugin(SnowTrip);
    }});await owner;ctx=rootContext;
    assert.equal(ctx.tools.schemas().some(tool=>tool.name.startsWith('snow_')),false,'宿主层不应注册雪季工具');
    agent={...agent};secondAgent={...agent,id:'second-session'};
    await ctx.snowTrip.listPackages();
    const presetKey={};
    await ctx.plugin({inject:['snowTrip','tools','userQuestions'],async apply(inner){
      presetScope=createScope(inner,presetKey);
      await presetScope.ctx.plugin(SnowTools);
    }});
    bindScopeParent(agent,presetKey);bindScopeParent(secondAgent,presetKey);
    assert.deepEqual(ctx.tools.schemas(agent).map(t=>t.name).sort(),['snow_query','snow_save_packages']);
    assert.deepEqual(ctx.tools.schemas(secondAgent).map(t=>t.name).sort(),['snow_query','snow_save_packages']);
    assert.deepEqual(ctx.tools.schemas({id:'ordinary-session'}),[]);
    assert.deepEqual(ctx.tools.schemas(),[]);
    const denied=await ctx.tools.execute({name:'snow_query',arguments:{},agent:{id:'ordinary-session'},signal:new AbortController().signal,callId:'denied'});
    assert.equal(denied.isError,true);
    return ctx.snowTrip.listPackages();
  }
  let agent={id:'test-session'};
  const execute=(name,args,signal=new AbortController().signal)=>ctx.tools.execute({name,arguments:args,agent,signal,callId:`call-${Math.random()}`});
  const input={package:{description:'长白山住宿',quote:129900,purchaseStatus:'unpurchased'}};
  try{
    assert.deepEqual(TYPERT.invocations.map(i=>i.id).sort(),['deletePackage','ensureWorkspace','getPackage','listPackages'].map(name=>`dsh-snow-trip#snowTrip/${name}`).sort());
    assert.deepEqual(await boot(),[]);
    for(const args of [{package:{}},{package:{...input.package,sourceNotes:[]}},{package:{...input.package,sources:[]}},{...input,confirmed:true},{package:{...input.package,confirmed:true}},{package:{...input.package,quote:-1}},{package:{...input.package,validFrom:'2026-02-30'}}]){
      const r=await execute('snow_save_packages',args);assert.equal(r.isError,true);assert.equal(r.meta,undefined);
    }
    assert.equal(calls,0);
    respond=()=>({answers:[{id:'save-package',selected:['暂不保存']}]});
    assert.equal((await execute('snow_save_packages',input)).isError,true);assert.deepEqual(await ctx.snowTrip.listPackages(),[]);
    respond=()=>({answers:[{id:'save-package',selected:['确认保存'],custom:'改成两晚'}]});
    assert.equal((await execute('snow_save_packages',input)).isError,true);
    respond=()=>({answers:[{id:'save-package',selected:['确认保存']}]});
    const success=await execute('snow_save_packages',input);
    assert.equal(success.isError,false,JSON.stringify(success));
    const record=packageMetadata(success.meta);assert.ok(record);
    assert.equal('sourceNotes' in record,false);
    assert.equal(record.revision,1);assert.equal(record.quote,129900);assert.equal(record.paid,null);
    assert.equal(record.nights,null);assert.equal('sources' in record,false);assert.equal(record.purchasePlatform,null);assert.equal(record.purchaseStatus,'unpurchased');
    assert.match(question,/报价：1299.00 元/);assert.match(question,/总间夜：待确认/);
    assert.deepEqual(await ctx.snowTrip.getPackage(record.id),record);
    const shared=await ctx.tools.execute({name:'snow_query',arguments:{},agent:secondAgent,signal:new AbortController().signal,callId:'shared'});
    assert.equal(shared.value.packages[0].id,record.id);
    const before=calls;respond=()=>({answers:[{id:'save-package',selected:['暂不保存']}]});
    assert.equal((await execute('snow_save_packages',{package:{...input.package,quote:200000}})).isError,true);
    assert.equal(calls,before+1);assert.match(question,/2000.00 元/);
    await owner.dispose();await boot();
    assert.deepEqual(await ctx.snowTrip.getPackage(record.id),record);
    const query=await execute('snow_query',{limit:1});assert.equal(query.isError,false,JSON.stringify(query));
    assert.equal('messages' in query.value,false);assert.equal(query.value.packages[0].id,record.id);assert.equal(query.value.truncated,false);
    respond=()=>({answers:[{id:'save-package',selected:['确认保存']}]});
    await execute('snow_save_packages',{package:{name:'另一个套餐'}});
    assert.equal((await execute('snow_query',{limit:1})).value.truncated,true);
    assert.equal((await execute('snow_query',{offset:1,limit:1})).value.packages.length,1);
    const update={id:record.id,expectedRevision:1,package:{purchasePlatform:'微信小程序 xxx',unavailableDates:['2026-12-25'],pendingQuestions:[]}};
    respond=()=>({answers:[{id:'save-package',selected:['暂不保存']}]});
    assert.equal((await execute('snow_save_packages',update)).isError,true);
    assert.equal((await ctx.snowTrip.getPackage(record.id)).revision,1);
    respond=()=>({answers:[{id:'save-package',selected:['确认保存']}]});
    const updated=await execute('snow_save_packages',update);
    assert.equal(updated.isError,false,JSON.stringify(updated));
    assert.equal(updated.value.id,record.id);assert.equal(updated.value.revision,2);
    assert.equal(updated.value.purchasePlatform,'微信小程序 xxx');assert.match(question,/购买平台：微信小程序 xxx/);assert.equal(updated.value.quote,record.quote);assert.equal(updated.value.createdAt,record.createdAt);
    assert.deepEqual(updated.value.unavailableDates,['2026-12-25']);
    assert.ok(!updated.value.unknowns.includes('不可用日期'));
    assert.equal((await ctx.snowTrip.listPackages()).length,2);
    const callsBeforeStale=calls;
    assert.equal((await execute('snow_save_packages',update)).isError,true);assert.equal(calls,callsBeforeStale);
    // 两个确认同时通过时，存储的原子版本检查只允许一个写入。
    let release;const gate=new Promise(resolve=>{release=resolve;});let arrivals=0;
    respond=async()=>{if(++arrivals===2)release();await gate;return {answers:[{id:'save-package',selected:['确认保存']}]};};
    const competing=await Promise.all([execute('snow_save_packages',{...update,expectedRevision:2,package:{roomType:'双床房'}}),execute('snow_save_packages',{...update,expectedRevision:2,package:{roomType:'大床房'}})]);
    assert.equal(competing.filter(r=>!r.isError).length,1);
    assert.equal((await ctx.snowTrip.getPackage(record.id)).revision,3);
    const count=(await ctx.snowTrip.listPackages()).length;
    const controller=new AbortController();respond=()=>{controller.abort();return {answers:[{id:'save-package',selected:['确认保存']}]};};
    assert.equal((await execute('snow_save_packages',input,controller.signal)).isError,true);
    respond=()=>({answers:[{id:'save-package',selected:['确认保存']}]});
    await rename(join(root,'snow_trip.json'),join(root,'saved.json'));await mkdir(join(root,'snow_trip.json'));
    const failure=await execute('snow_save_packages',input);assert.equal(failure.isError,true);assert.equal(failure.meta,undefined);
    assert.equal((await ctx.snowTrip.listPackages()).length,count);
    await assert.rejects(ctx.snowTrip.deletePackage(record.id,3,false));
    assert.equal((await ctx.snowTrip.listPackages()).length,count,'删除写盘失败保留记录');
    await rm(join(root,'snow_trip.json'),{recursive:true});await rename(join(root,'saved.json'),join(root,'snow_trip.json'));
    await assert.rejects(ctx.snowTrip.deletePackage(record.id,2,false),/已变更/);
    await assert.rejects(ctx.snowTrip.deletePackage(record.id,3,true),/关联套餐已变更/);
    assert.deepEqual(await ctx.snowTrip.deletePackage(record.id,3,false),{sessionId:null,archiveError:null},'同会话还有套餐时不归档');
    const remaining=(await ctx.snowTrip.listPackages())[0];
    await assert.rejects(ctx.snowTrip.deletePackage(remaining.id,remaining.revision,false),/关联套餐已变更/);
    let finishArchive,archiveStarted;
    const started=new Promise(resolve=>{archiveStarted=resolve;});
    onArchive=()=>{archiveStarted();return new Promise(resolve=>{finishArchive=resolve;});};
    const deleting=ctx.snowTrip.deletePackage(remaining.id,remaining.revision,true);
    await started;
    const later={...remaining,id:crypto.randomUUID()};
    const saving=ctx.snowTrip.savePackage(later);
    await new Promise(resolve=>setImmediate(resolve));
    assert.equal(await ctx.snowTrip.getPackage(later.id),null,'归档完成前其他写入必须等待');
    finishArchive();
    assert.deepEqual(await deleting,{sessionId:remaining.sessionId,archiveError:null});
    await saving;
    onArchive=async()=>{throw new Error('归档写盘失败');};
    assert.deepEqual(await ctx.snowTrip.deletePackage(later.id,later.revision,true),{sessionId:null,archiveError:'归档写盘失败'});
    assert.equal(await ctx.snowTrip.getPackage(later.id),null,'归档失败时明确返回删除已完成');
    onArchive=async()=>{};
    await assert.rejects(ctx.snowTrip.deletePackage(remaining.id,remaining.revision,true),/已变更/);
    assert.deepEqual(archived,[remaining.sessionId]);
    await owner.dispose();await boot();
    assert.deepEqual(await ctx.snowTrip.listPackages(),[],'重启后仍然删除');
    assert.equal(packageMetadata({...success.meta,version:99}),null);
    await presetScope.dispose();
    assert.deepEqual(ctx.tools.schemas(agent),[]);
    assert.equal((await ctx.snowTrip.listPackages()).length,0);
  }finally{await owner?.dispose();await rm(root,{recursive:true,force:true});}
});
