// pnpm build 后运行；SNOW_DSH_CLI 指向已有 DSH CLI，使用临时 profile 和真实认证 Remote。
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {Context} from '@deepseek-ai/cordis';
import Storage from '@deepseek-ai/dsh-storage';
import * as StorageJson from '@deepseek-ai/dsh-storage-json';
import * as StorageDomain from '@deepseek-ai/dsh-storage-domain';
import {SnowTrip} from '../lib/server/service.js';
import {normalizePackage} from '../src/shared/packages.ts';
const {chromium}=await import(process.env.SNOW_PLAYWRIGHT||'playwright');
assert.ok(process.env.SNOW_DSH_CLI,'请提供 SNOW_DSH_CLI');
const home=await mkdtemp(join(tmpdir(),'snow-home-calendar-')),env={...process.env,DSH_HOME:home};
const ctx=new Context();let owner,server,browser,releaseRead=()=>{};
const now=new Date().toISOString(),aId=crypto.randomUUID(),cId=crypto.randomUUID(),unknownId=crypto.randomUUID();
const a={...normalizePackage({name:'跨年套餐 A',hotels:['合成酒店'],nights:3,usedNights:0,voided:false,validFrom:'2026-12-30',validTo:'2027-01-02',unavailableDates:['2027-01-01'],splitAllowed:false,splitRule:'每次至少连住三晚',surchargeRules:['节假日补款待核对'],purchaseStatus:'purchased'}),id:aId,revision:1,schemaVersion:1,createdAt:now,updatedAt:now,sessionId:'home-fixture'};
const c={...a,id:cId,name:'日期待确认套餐 C',unavailableDates:null};
const unknown={...c,id:unknownId,name:'无日期套餐',validFrom:null,validTo:null};
const plan={id:crypto.randomUUID(),schemaVersion:1,createdAt:now,sessionId:'home-fixture',title:'跨年方案 B',start:'2026-12-31',nights:2,budget:null,total:null,paid:null,pending:null,reason:null,allocation:null,estimates:[],items:[{packageId:aId,revision:1,start:'2026-12-31',nights:2}],daily:[],sharedCosts:[],unknowns:[],packages:[{id:aId,revision:1,snapshot:a}],tracking:{booking:'unreserved',refund:null,refundPolicy:null}};
try{
  owner=ctx.plugin({async apply(inner){await inner.plugin(Storage);await inner.plugin(StorageJson,{root:join(home,'storages')});await inner.plugin(StorageDomain,{backend:'json'});inner.provide('workspaceRegistry',{archiveSession:async()=>{}});await inner.plugin(SnowTrip);}});
  await owner;
  for(const record of [a,c,unknown])await ctx.snowTrip.savePackage(record);
  await ctx.snowTrip.savePlan(plan);await owner.dispose();owner=null;
  for(const plugin of [process.cwd(),resolve('test/integration-host')])await promisify(execFile)(process.execPath,[process.env.SNOW_DSH_CLI,'plugin','--profile','web','add',plugin],{env});
  server=spawn(process.execPath,[process.env.SNOW_DSH_CLI,'web','--no-open','--host','127.0.0.1','--port','0'],{env,stdio:['ignore','pipe','pipe']});
  const url=await new Promise((resolveURL,reject)=>{
    let log='';const timer=setTimeout(()=>reject(new Error('隔离宿主启动超时')),45000);
    const read=data=>{log+=data;const match=log.match(/http:\/\/127\.0\.0\.1:\d+[^\s\x1b]*/);if(match){clearTimeout(timer);resolveURL(match[0]);}};
    server.stdout.on('data',read);server.stderr.on('data',read);
    server.once('exit',code=>{clearTimeout(timer);reject(new Error(`隔离宿主退出：${code}`));});
  });
  browser=await chromium.launch({headless:true,executablePath:process.env.SNOW_CHROME});
  const page=await browser.newPage({viewport:{width:1507,height:858}}),errors=[];
  page.on('crash',()=>console.error('浏览器页面崩溃'));
  page.setDefaultTimeout(10000);page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});
  await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.snowSessionCheck);
  await page.getByRole('button',{name:'继续',exact:true}).click();
  await page.getByRole('button',{name:'稍后配置',exact:true}).click();
  assert.equal((await page.evaluate(()=>window.snowSessionCheck.listPackages())).value.length,3);
  const unauthorized=await fetch(new URL('/api/snowTrip/listPackages',url),{method:'POST',headers:{'Content-Type':'application/json',Origin:new URL(url).origin},body:JSON.stringify({args:{}})});
  assert.ok([401,403].includes(unauthorized.status));
  await page.getByRole('button',{name:'打开雪季出行工作台',exact:true}).click();
  const panel=page.getByRole('dialog',{name:'雪季出行工作台',exact:true}),calendar=panel.getByRole('region',{name:'首页月历',exact:true});
  const brand=()=>panel.getByRole('button',{name:'雪季出行，返回首页',exact:true}).filter({visible:true}).first();
  const day=value=>calendar.getByRole('button',{name:new RegExp('^'+value+'，')});
  const expectDay=async(value,text)=>{await page.waitForFunction(({value,text})=>document.querySelector(`.snow-home button[aria-label^="${value}，"]`)?.getAttribute('aria-label')===text,{value,text});};
  await calendar.waitFor().catch(async error=>{console.error(await panel.innerText());throw error;});
  await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  assert.equal(await calendar.locator('.snow-season-navigation,.snow-season-layers,.snow-season-selection').count(),0);
  assert.equal(await calendar.locator('.rdp-month_grid').count(),4);
  assert.deepEqual(await calendar.locator('.snow-season-month').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label'))),['2026年12月','2027年1月','2027年2月','2027年3月']);
  await calendar.evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(animation=>animation.finished)));
  const bounds=await calendar.locator('.snow-season-month').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom};}));
  assert.ok(bounds.every(r=>Math.abs(r.top-bounds[0].top)<1&&r.bottom<=858),'桌面四个月必须同时完整显示在一屏内');
  assert.deepEqual(await calendar.locator('.snow-season-totals strong').allTextContents(),['1','3','1']);
  assert.match(await calendar.locator('.rdp-weekday').first().innerText(),/一/);
  const chooseMonths=async(start,end)=>{
    await calendar.getByRole('button',{name:/^展示月份：/}).click();
    const picker=page.getByRole('group',{name:'展示月份选项',exact:true});
    await picker.getByRole('button',{name:start,exact:true}).click();
    assert.equal(await picker.getByRole('button',{name:'确定区间',exact:true}).isEnabled(),false);
    await picker.getByRole('button',{name:end,exact:true}).click();
    await picker.getByRole('button',{name:'确定区间',exact:true}).click();
  };
  await chooseMonths('2027年1月','2027年1月');
  assert.equal(await calendar.locator('.rdp-month_grid').count(),1);
  assert.deepEqual(await calendar.locator('.snow-season-totals strong').allTextContents(),['1','2','1']);
  await page.waitForFunction(async()=>{const db=await new Promise(resolve=>{const req=indexedDB.open('dsh-snow-trip');req.onsuccess=()=>resolve(req.result);});try{return await new Promise(resolve=>{const req=db.transaction('data').objectStore('data').get('home-month-range');req.onsuccess=()=>resolve(req.result?.start==='2027-01'&&req.result?.end==='2027-01');});}finally{db.close();}});
  await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button',{name:'稍后配置',exact:true}).click();
  await page.getByRole('button',{name:'打开雪季出行工作台',exact:true}).click();
  await calendar.getByRole('button',{name:'展示月份：2027-01 至 2027-01',exact:true}).waitFor();
  assert.equal(await calendar.locator('.rdp-month_grid').count(),1);
  await chooseMonths('2027年12月','2026年1月');
  assert.equal(await calendar.locator('.rdp-month_grid').count(),24);
  await chooseMonths('2026年12月','2027年3月');
  await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');

  await day('2026-12-31').hover();
  const tooltip=calendar.locator('#snow-date-2026-12-31');await tooltip.waitFor({state:'visible'});
  assert.match(await tooltip.innerText(),/跨年方案 B/);assert.match(await tooltip.innerText(),/跨年套餐 A/);
  assert.equal(await day('2026-12-31').getAttribute('data-marked'),'true');
  assert.equal(await day('2026-12-31').getAttribute('data-package'),'true');
  assert.equal(await day('2026-12-31').getAttribute('data-pending'),'true');
  await day('2026-12-31').press('Escape');await tooltip.waitFor({state:'hidden'});
  const legend=calendar.getByRole('group',{name:'日期图例'});
  await legend.getByRole('button',{name:'套餐当晚可用',exact:true}).click();
  assert.equal(await day('2026-12-31').getAttribute('data-marked'),null);
  assert.equal(await day('2026-12-31').getAttribute('data-package'),'true');
  assert.equal(await day('2026-12-31').getAttribute('data-pending'),null);
  for(const name of ['已确认行程','待预约 / 状态未知','套餐日期待确认'])await legend.getByRole('button',{name,exact:true}).click();
  await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  for(const name of ['已确认行程','待预约 / 状态未知','套餐当晚可用','套餐日期待确认'])await legend.getByRole('button',{name,exact:true}).click();
  await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  await panel.getByRole('button',{name:/^已录套餐/}).click();await brand().press('Enter');
  await panel.getByRole('button',{name:/^已存方案/}).click();
  await panel.getByRole('button',{name:'继续规划',exact:true}).click();
  const missing=page.getByRole('dialog',{name:'原会话不可用',exact:true});await missing.waitFor();
  await missing.getByRole('button',{name:'新建会话继续',exact:true}).click();
  const editor=panel.locator('.snow-conversation [contenteditable=true]');await editor.waitFor();
  await editor.fill('保留未发送的雪季验收草稿');await brand().click();
  await panel.getByRole('button',{name:'继续未发送的会话',exact:true}).click();
  assert.match(await editor.innerText(),/保留未发送的雪季验收草稿/);
  await brand().press('Escape');await panel.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'打开雪季出行工作台',exact:true}).click();await calendar.waitFor();
  await panel.getByRole('button',{name:'继续未发送的会话',exact:true}).click();assert.match(await editor.innerText(),/保留未发送的雪季验收草稿/);
  await brand().click();
  console.log('通过：认证读取、四个月一屏总览、统计去重、叠加标记、图例筛选、悬停详情与未发送草稿。');
  await page.setViewportSize({width:390,height:844});await day('2027-01-02').press('ArrowRight');await page.keyboard.press('Enter');
  await calendar.locator('#snow-date-2027-01-03').waitFor({state:'visible'});
  assert.equal(await panel.locator('.snow-content').evaluate(el=>el.scrollWidth>el.clientWidth),false);
  await calendar.evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(animation=>animation.finished)));
  const mobileBounds=await calendar.locator('.snow-season-month').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().top));
  assert.equal(mobileBounds[0],mobileBounds[1]);assert.equal(mobileBounds[2],mobileBounds[3]);assert.ok(mobileBounds[2]>mobileBounds[0]);
  await panel.getByRole('button',{name:'打开菜单',exact:true}).click();await panel.getByRole('button',{name:/^已存方案/}).click();
  await panel.getByRole('button',{name:'打开菜单',exact:true}).click();await brand().press('Enter');await calendar.waitFor();
  await panel.getByRole('button',{name:'打开菜单',exact:true}).click();await panel.locator('#snow-sidebar .brand').press('Space');
  assert.equal(await page.getByRole('dialog',{name:'雪季导航',exact:true}).isVisible(),false);
  await calendar.evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(animation=>animation.finished)));
  await mkdir('.local/home-calendar',{recursive:true});await page.screenshot({path:'.local/home-calendar/mobile.png'});
  await page.setViewportSize({width:1507,height:858});await day('2026-12-31').click();
  await page.screenshot({path:'.local/home-calendar/desktop.png'});
  await page.emulateMedia({reducedMotion:'reduce',colorScheme:'dark'});
  assert.equal(await calendar.locator('.snow-season-month').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.screenshot({path:'.local/home-calendar/dark.png'});await page.emulateMedia({reducedMotion:'no-preference',colorScheme:'light'});
  console.log('通过：键盘、窄屏双列、减少动态效果和深色模式。');
  // 真实 Remote 响应延迟与网络失败：不替换内部 actions 或记录计算。
  let arrived;
  const held=new Promise(resolve=>{arrived=resolve;}),gate=new Promise(resolve=>{releaseRead=resolve;});
  await page.route('**/api/snowTrip/listPackages',async route=>{const response=await route.fetch();arrived();await gate;try{await route.fulfill({response});}catch(error){if(!/already handled|closed/.test(error.message))throw error;}},{times:1});
  await panel.getByRole('button',{name:/^已录套餐/}).click();await held;
  await page.route('**/api/snowTrip/listPackages',route=>route.abort());await brand().click();
  await calendar.getByText(/套餐读取失败：/).waitFor();await expectDay('2026-12-31','2026-12-31，方案 1，套餐 —');
  await page.unroute('**/api/snowTrip/listPackages');await calendar.getByRole('button',{name:'重试套餐',exact:true}).click();await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  let releasePlans,plansArrived;
  const plansHeld=new Promise(resolve=>{plansArrived=resolve;}),plansGate=new Promise(resolve=>{releasePlans=resolve;});
  await panel.getByRole('button',{name:/^已录套餐/}).click();
  await page.route('**/api/snowTrip/listPlans',async route=>{const response=await route.fetch();plansArrived();await plansGate;await route.fulfill({response});},{times:1});
  await brand().click();await plansHeld;
  await calendar.getByText('正在读取方案…',{exact:true}).waitFor();await expectDay('2026-12-31','2026-12-31，方案 —，套餐 1，待确认 1');
  releasePlans();await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  await page.route('**/api/snowTrip/listPlans',route=>route.abort());
  await panel.getByRole('button',{name:/^已录套餐/}).click();await brand().click();
  await calendar.getByText(/方案读取失败：/).waitFor();await expectDay('2026-12-31','2026-12-31，方案 —，套餐 1，待确认 1');
  await page.unroute('**/api/snowTrip/listPlans');await calendar.getByRole('button',{name:'重试方案',exact:true}).click();await expectDay('2026-12-31','2026-12-31，方案 1，套餐 1，待确认 1');
  // 删除 A 同时删除 B，之后释放旧请求，不能让旧记录重新出现。
  await panel.getByRole('button',{name:/^已录套餐/}).click();
  await panel.locator(`.package-candidates [data-package-id="${aId}"]`).getByRole('button',{name:'删除套餐',exact:true}).click();
  await page.getByRole('dialog',{name:'删除套餐',exact:true}).getByRole('button',{name:'确认删除',exact:true}).click();
  await page.getByRole('dialog',{name:'删除套餐',exact:true}).waitFor({state:'hidden'});await brand().click();
  await expectDay('2026-12-31','2026-12-31，方案 0，套餐 0，待确认 1');releaseRead();
  await page.waitForLoadState('networkidle');await expectDay('2026-12-31','2026-12-31，方案 0，套餐 0，待确认 1');
  for(const id of [cId,unknownId]){
    await panel.getByRole('button',{name:/^已录套餐/}).click();await panel.locator(`.package-candidates [data-package-id="${id}"]`).getByRole('button',{name:'删除套餐',exact:true}).click();
    await page.getByRole('dialog',{name:'删除套餐',exact:true}).getByRole('button',{name:'确认删除',exact:true}).click();await page.getByRole('dialog',{name:'删除套餐',exact:true}).waitFor({state:'hidden'});
  }
  await brand().click();await calendar.getByRole('button',{name:'开始录入第一份套餐',exact:true}).waitFor();
  await panel.getByRole('button',{name:'出发去山野',exact:true}).click();
  const departure=panel.locator('.snow-conversation'),draft=departure.locator('[data-composer-input]');
  await draft.fill('技能切换保留草稿');
  await departure.getByRole('button',{name:/录入套餐/}).click();
  await page.waitForFunction(()=>document.querySelector('.snow-conversation [data-composer-input]')?.textContent.includes('/snow-import'));
  assert.match(await draft.innerText(),/^\/snow-import 技能切换保留草稿$/);
  await departure.getByRole('button',{name:/规划出行/}).click();
  await departure.getByRole('button',{name:/规划出行/}).click();
  assert.match(await draft.innerText(),/^\/snow-plan 技能切换保留草稿$/);
  assert.deepEqual(errors,[]);
  console.log('通过：真实宿主认证、默认首页、四个月总览、无明细卡片、重开与草稿、固定雪季、键盘与窄屏、读取失败与重试、级联删除、迟到响应、空库和技能切换保留草稿。');
}finally{
  releaseRead();
  await browser?.close();
  if(server&&server.exitCode===null){server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}
  await owner?.dispose();await rm(home,{recursive:true,force:true});
}
