// 仅使用合成数据；SNOW_PLAYWRIGHT、SNOW_REACT_DOM 指向已有依赖。
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile,mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.SNOW_PLAYWRIGHT||'playwright');
const script=await build({stdin:{contents:`
import React from 'react';import {createRoot} from ${JSON.stringify(process.env.SNOW_REACT_DOM||'react-dom/client')};
import {App} from './src/client/workbench.jsx';import {normalizePackage} from './src/shared/packages.ts';import {storage} from './src/client/storage.js';
const id='11111111-1111-4111-8111-111111111111',createdAt='2026-09-25T00:00:00Z';
const pkg={...normalizePackage({name:'测试套餐',region:'吉林'}),id,revision:1,schemaVersion:1,createdAt,updatedAt:createdAt,sessionId:'test'};
const plan={id,schemaVersion:1,createdAt,sessionId:'test',title:'删除验收方案',start:'2027-02-06',nights:7,budget:null,total:10000,paid:null,pending:null,reason:null,allocation:null,estimates:[],items:[{packageId:id,revision:1,nights:7,start:'2027-02-06'}],daily:[{date:'2027-02-06',packageId:id,amount:10000,basis:null}],sharedCosts:[],unknowns:[],packages:[{id,revision:1,snapshot:pkg}]};
window.check={template:plan,plans:[plan,{...plan,id:'22222222-2222-4222-8222-222222222222',title:'可退方案',nights:2,total:0,packages:[{id,revision:1,snapshot:{...pkg,region:'黑龙江'}}],tracking:{booking:'unreserved',refund:'refundable',refundPolicy:'未预约可退'}},{...plan,id:'33333333-3333-4333-8333-333333333333',title:'不可退方案',total:20000,tracking:{booking:'confirmed',refund:'nonrefundable',refundPolicy:null}}],packages:[{...pkg,name:'最新套餐名称',revision:2,region:'新疆'}],fail:false,calls:0,prompt:null,missing:false,created:0};
const workspace={archivedSessionIds:[]},sessions={byId:{test:{id:'test',title:'关联会话',projectionValues:{agentPreset:'snow-trip'}}},ids:['test']};
const actions={selection:{subscribe:()=>()=>{},getSnapshot:()=>null},lastSession:()=>null,workspaceList:{subscribe:()=>()=>{},getSnapshot:()=>workspace},listPackages:async()=>window.check.packages,listPlans:async()=>[...window.check.plans],sessionState:()=>null,continueRecord:async(record,prompt)=>{if(window.check.missing)return false;window.check.prompt=prompt;sessions.current=record.sessionId;render();return true;},create:async prompt=>{window.check.created++;window.check.prompt=prompt;},deletePlan:async id=>{window.check.calls++;await new Promise(r=>setTimeout(r,100));if(window.check.fail)throw new Error('模拟写入失败');window.check.plans=window.check.plans.filter(p=>p.id!==id);}};
await storage('plans',[{id:'legacy',title:'不应显示的旧方案'}]);
const root=createRoot(document.getElementById('root'));function render(){root.render(<App useSessionStatus={()=>new Map()} useSessions={()=>sessions} renderSlot={()=>null} actions={actions}/>);}render();
`,resolveDir:process.cwd(),loader:'jsx'},bundle:true,write:false,format:'esm',alias:{react:process.cwd()+'/node_modules/react'},jsx:'automatic'});
const browser=await chromium.launch({headless:true,executablePath:process.env.SNOW_CHROME});
try{
 const page=await browser.newPage({viewport:{width:1061,height:863}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.setDefaultTimeout(5000);
 await page.route('http://snow.test/',route=>route.fulfill({body:'<meta charset="utf-8"><div id="root"></div>',contentType:'text/html'}));
 await page.goto('http://snow.test/');await page.addStyleTag({content:await readFile('node_modules/react-day-picker/src/style.css','utf8')+'\n'+await readFile('src/client/style.css','utf8')});await page.addScriptTag({type:'module',content:script.outputFiles[0].text});
 await page.getByRole('button',{name:/^已存方案/}).click();
 const cards=page.locator('.snow-saved-card'),filters=page.getByRole('region',{name:'方案筛选'});
 const totals=page.getByRole('region',{name:'方案总数统计'}).locator('strong');
 assert.deepEqual(await totals.allTextContents(),['3 份','1 份','1 份','1 份']);
 assert.equal(await cards.count(),3);
 const sortTrigger=page.getByRole('button',{name:/^排序：/}),sortArea=page.locator('.snow-package-sort');
 const titles=()=>cards.locator('h3').allTextContents();
 assert.deepEqual(await titles(),['删除验收方案','不可退方案','可退方案']);
 await page.getByRole('button',{name:'当前降序，切换为升序'}).click();
 assert.deepEqual(await titles(),['可退方案','删除验收方案','不可退方案']);
 await sortTrigger.click();
 assert.deepEqual(await page.getByRole('radiogroup',{name:'排序',exact:true}).getByRole('radio').evaluateAll(nodes=>nodes.map(node=>node.parentElement.textContent)),['出行天数','整趟总成本']);
 await page.getByRole('radio',{name:'整趟总成本',exact:true}).click();
 assert.deepEqual(await titles(),['可退方案','删除验收方案','不可退方案']);
 await page.getByRole('button',{name:'当前升序，切换为降序'}).click();
 assert.deepEqual(await titles(),['不可退方案','删除验收方案','可退方案']);
 await sortTrigger.click();await page.getByRole('radio',{name:'出行天数',exact:true}).click();
 assert.deepEqual(await titles(),['删除验收方案','不可退方案','可退方案']);
 await sortArea.screenshot({path:'.local/plan-sort-desktop.png'});

 const regionTrigger=filters.getByRole('button',{name:/^出行目的地：/});
 await regionTrigger.click();
 const regions=page.getByRole('group',{name:'出行目的地选项',exact:true});
 assert.deepEqual(await regions.getByRole('checkbox').evaluateAll(nodes=>nodes.map(node=>node.parentElement.textContent)),['黑龙江','吉林']);
 await regions.getByRole('checkbox',{name:'黑龙江',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),1);assert.match(await cards.innerText(),/可退方案/);
 await regionTrigger.click();await regions.getByRole('checkbox',{name:'吉林',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),3);
 await filters.getByRole('button',{name:'重置筛选'}).click();assert.match(await regionTrigger.innerText(),/全部/);
 await filters.getByRole('button',{name:'方案标签：全部标签',exact:true}).click();
 const statuses=page.getByRole('group',{name:'方案标签选项',exact:true});
 assert.equal(await statuses.getByRole('checkbox').count(),6);
 assert.equal(await statuses.getByRole('group',{name:'预约状态',exact:true}).getByRole('checkbox').count(),3);
 assert.equal(await statuses.getByRole('group',{name:'退改状态',exact:true}).getByRole('checkbox').count(),3);
 assert.equal(await filters.getByRole('button',{name:/^(预约状态|退改状态)：/}).count(),0);
 await statuses.getByRole('group',{name:'预约状态',exact:true}).getByRole('checkbox',{name:'已确认',exact:true}).check();
 await statuses.getByRole('group',{name:'退改状态',exact:true}).getByRole('checkbox',{name:'不可退',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),1);
 assert.equal((await totals.allTextContents())[0],'3 份');
 await page.keyboard.press('Escape');
 await filters.getByRole('button',{name:'可退策略：全部',exact:true}).click();
 await page.getByRole('group',{name:'可退策略选项',exact:true}).getByRole('checkbox',{name:'未预约可退',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 await page.keyboard.press('Escape');
 await page.getByRole('heading',{name:'没有符合条件的方案'}).waitFor();
 await filters.getByRole('button',{name:'重置筛选'}).click();
 await filters.getByRole('button',{name:'方案标签：全部标签',exact:true}).click();
 await statuses.getByRole('group',{name:'预约状态',exact:true}).getByRole('checkbox',{name:'已确认',exact:true}).check();
 await statuses.getByRole('group',{name:'退改状态',exact:true}).getByRole('checkbox',{name:'不可退',exact:true}).check();
 await statuses.getByRole('group',{name:'预约状态',exact:true}).getByRole('checkbox',{name:'未预约',exact:true}).check();
 await statuses.getByRole('group',{name:'退改状态',exact:true}).getByRole('checkbox',{name:'可退',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),2);
 await filters.getByRole('button',{name:'重置筛选'}).click();
 assert.equal(await cards.count(),3);
 const tags=filters.getByRole('button',{name:/^方案标签：/});
 assert.match(await tags.innerText(),/全部标签/);
 await tags.click();
 await statuses.getByRole('group',{name:'预约状态',exact:true}).getByRole('checkbox',{name:'未设置',exact:true}).check();
 assert.match(await tags.innerText(),/预约状态未设置/);
 await page.keyboard.press('Escape');
 assert.equal(await tags.evaluate(node=>document.activeElement===node),true);
 await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),1);assert.match(await cards.innerText(),/删除验收方案/);
 await filters.getByRole('button',{name:'重置筛选'}).click();
 await filters.getByRole('button',{name:'出行天数：全部',exact:true}).click();
 assert.deepEqual(await page.getByRole('group',{name:'出行天数选项',exact:true}).getByRole('checkbox').evaluateAll(nodes=>nodes.map(node=>node.parentElement.textContent)),['3 天','8 天']);
 await page.getByRole('checkbox',{name:'3 天',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),1);
 assert.match(await cards.innerText(),/可退方案/);
 await filters.getByRole('button',{name:'出行天数：3 天',exact:true}).click();
 assert.equal(await page.getByRole('checkbox',{name:'8 天',exact:true}).count(),1);
 await page.getByRole('checkbox',{name:'8 天',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),3);
 await filters.getByRole('button',{name:'重置筛选'}).click();
 await filters.getByRole('button',{name:'出行天数：全部',exact:true}).waitFor();
 const dateTrigger=filters.getByRole('button',{name:/^出行时间：/}),calendar=page.getByRole('group',{name:'出行时间选项',exact:true});
 const selectRange=async(start,end)=>{
   await dateTrigger.click();
   await calendar.getByLabel('选择年份',{exact:true}).selectOption(start.slice(0,4));
   await calendar.getByLabel('选择月份',{exact:true}).selectOption(String(Number(start.slice(5,7))-1));
   await calendar.getByRole('button',{name:start,exact:true}).click();
   assert.equal(await calendar.getByRole('button',{name:'确定区间'}).isDisabled(),true);
   if(start.slice(0,7)!==end.slice(0,7)){
     await calendar.getByLabel('选择年份',{exact:true}).selectOption(end.slice(0,4));
     await calendar.getByLabel('选择月份',{exact:true}).selectOption(String(Number(end.slice(5,7))-1));
   }
   await calendar.getByRole('button',{name:end,exact:true}).click();
   await calendar.getByRole('button',{name:'确定区间'}).click();
 };
 await selectRange('2027-12-30','2028-01-03');
 assert.match(await dateTrigger.innerText(),/2027-12-30 至 2028-01-03/);
 await selectRange('2028-02-29','2028-03-01');
 assert.match(await dateTrigger.innerText(),/2028-02-29 至 2028-03-01/);
 await selectRange('2027-02-08','2027-02-13');
 assert.equal(await cards.count(),3);
 assert.match(await dateTrigger.innerText(),/2027-02-08 至 2027-02-13/);
 await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),2);
 assert.equal((await totals.allTextContents())[0],'3 份');
 // 关闭未完成的选择时保留上次完整区间。
 await dateTrigger.click();await calendar.getByRole('button',{name:'2027-02-10',exact:true}).click();
 await page.keyboard.press('Escape');
 assert.equal(await dateTrigger.evaluate(node=>node===document.activeElement),true);
 assert.match(await dateTrigger.innerText(),/2027-02-08 至 2027-02-13/);
 await selectRange('2027-02-08','2027-02-14');
 await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 await page.getByRole('heading',{name:'没有符合条件的方案'}).waitFor();
 await selectRange('2027-02-13','2027-02-08');
 assert.match(await dateTrigger.innerText(),/2027-02-08 至 2027-02-13/);
 await dateTrigger.click();await calendar.getByRole('button',{name:'清空日期'}).click();
 assert.match(await dateTrigger.innerText(),/不限日期/);
 await filters.getByRole('button',{name:'重置筛选'}).click();
 assert.equal(await cards.count(),3);
 assert.equal(await page.getByRole('button',{name:'编辑出行标签'}).count(),0);
 assert.equal(await cards.locator('form,input,select,textarea').count(),0);
 // 模拟工具保存后的服务端数据，切回工作台时读取最新标签。
 await page.evaluate(()=>{window.check.plans[0].tracking={booking:'confirmed',refund:'refundable',refundPolicy:'2月4日00:00前可退'};});
 await page.getByRole('button',{name:/^已录套餐/}).click();
 await page.getByRole('button',{name:/^已存方案/}).click();
 await cards.first().getByText('可退策略：2月4日00:00前可退',{exact:true}).waitFor();
 assert.deepEqual(await totals.allTextContents(),['3 份','2 份','2 份','1 份']);
 await filters.scrollIntoViewIfNeeded();await page.waitForTimeout(200);
 await filters.getByRole('button',{name:'可退策略：全部',exact:true}).click();
 assert.equal(await page.getByRole('checkbox').count(),2);
 await page.getByRole('checkbox',{name:'2月4日00:00前可退',exact:true}).check();
 await page.keyboard.press('Escape');await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 await page.keyboard.press('Escape');
 assert.equal(await cards.count(),1);
 assert.equal((await totals.allTextContents())[0],'3 份');
 assert.match(await cards.innerText(),/已确认.*可退/s);
 await filters.scrollIntoViewIfNeeded();
 await page.screenshot({path:'.local/plan-filters-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await filters.getByRole('button',{name:/筛选方案/}).click();
 await filters.getByRole('button',{name:'查找方案',exact:true}).waitFor();
 await page.screenshot({path:'.local/plan-filters-mobile.png'});
 await page.getByRole('button',{name:'当前降序，切换为升序'}).focus();await page.keyboard.press('Enter');
 await page.getByRole('button',{name:'当前升序，切换为降序'}).waitFor();
 await sortArea.screenshot({path:'.local/plan-sort-mobile.png'});
 await page.keyboard.press('Space');
 await page.getByRole('button',{name:'当前降序，切换为升序'}).waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.deepEqual(errors,[]);
 await selectRange('2027-02-13','2027-02-13');
 await filters.getByRole('button',{name:'查找方案',exact:true}).click();
 assert.equal(await cards.count(),1);
 await filters.getByRole('button',{name:/筛选方案/}).click();
 assert.match(await dateTrigger.innerText(),/2027-02-13 至 2027-02-13/);
 await dateTrigger.click();
 await calendar.locator('.rdp-root').waitFor();
 const bounds=await calendar.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390&&bounds.y>=0&&bounds.y+bounds.height<=844);
 assert.equal(await calendar.evaluate(node=>node.scrollWidth>node.clientWidth),false);
 assert.equal(await calendar.getByRole('button',{name:'下个月',exact:true}).locator('svg').isVisible(),true);
 await calendar.getByRole('button',{name:'2027-02-08',exact:true}).click();
 await calendar.getByRole('button',{name:'2027-02-13',exact:true}).click();
 assert.equal(await calendar.locator('.rdp-range_middle').count(),4);
 await page.screenshot({path:'.local/plan-date-range-mobile.png'});
 await page.setViewportSize({width:320,height:740});
 await dateTrigger.click();await calendar.locator('.rdp-root').waitFor();
 assert.equal(await calendar.evaluate(node=>node.scrollWidth>node.clientWidth),false);
 const narrow=await calendar.boundingBox();assert.ok(narrow.x>=0&&narrow.x+narrow.width<=320);
 await page.keyboard.press('Escape');
 console.log('方案天数、日期区间包含、日期校验、组合筛选与窄屏检查通过');
}finally{await browser.close();}
